# **IPL Data Analysis**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#loading the datasets

matches_df=pd.read_csv("/content/IPL Matches 2008-2020.csv")
balls_df=pd.read_csv("/content/IPL Ball-by-Ball 2008-2020.csv")

In [ ]:
matches_df.head(2)

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri

In [ ]:
balls_df.head(2)

,id,inning,over,ball,batsman,non_striker,bowler,batsman_runs,extra_runs,total_runs,non_boundary,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team
0,335982,1,6,5,RT Ponting,BB McCullum,AA Noffke,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
1,335982,1,6,6,BB McCullum,RT Ponting,AA Noffke,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore

In [ ]:
#1. What was the count of matches played in each season?

matches_df['date']=pd.to_datetime(matches_df['date'])
matches_df['season']=matches_df['date'].dt.year

matches_df['season'].value_counts().sort_index()

season
2008    58
2009    57
2010    60
2011    73
2012    74
2013    76
2014    60
2015    59
2016    60
2017    59
2018    60
2019    60
2020    60
Name: count, dtype: int64

In [ ]:
#2. How many runs were scored in each season?

merged_df = pd.merge(balls_df, matches_df[["id", "season"]], on="id")
merged_df.groupby('season').total_runs.sum()

balls_df

,id,inning,over,ball,batsman,non_striker,bowler,batsman_runs,extra_runs,total_runs,non_boundary,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team
0,335982,1,6,5,RT Ponting,BB McCullum,AA Noffke,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
1,335982,1,6,6,BB McCullum,RT Ponting,AA Noffke,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
2,335982,1,7,1,BB McCullum,RT Ponting,Z Khan,0,0,0,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
3,335982,1,7,2,BB McCullum,RT Ponting,Z Khan,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
4,335982,1,7,3,RT Ponting,BB McCullum,Z Khan,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193463,1237181,1,12,5,RR Pant,SS Iyer,NM Coulter-Nile,0,0,0,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians
193464,1237181,1,12,6,RR Pant,SS Iyer,NM Coulter-Nile,1,0,1,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians
193465,1237181,1,13,1,RR Pant,SS Iyer,KH Pandya,0,1,1,0,0,NaN,NaN,NaN,wides,Delhi Capitals,Mumbai Indians
193466,1237181,1,13,2,RR Pant,SS Iyer,KH Pandya,1,0,1,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians
193467,1237181,1,13,3,SS Iyer,RR Pant,KH Pandya,1,0,1,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians

In [ ]:
#3. What were the runs scored per match in different seasons?

merged_df.groupby(['season','id']).total_runs.sum()

season  id
2008    335982     304
        335983     447
        335984     261
        335985     331
        335986     222
                  ...
2020    1216547    402
        1237177    343
        1237178    263
        1237180    361
        1237181    313
Name: total_runs, Length: 816, dtype: int64

In [ ]:
#4. Who has umpired the most?

#matches_df['umpire1'].value_counts().idxmax()

pd.concat([matches_df["umpire1"], matches_df["umpire2"]]).value_counts().idxmax()

'S Ravi'

In [ ]:
#5. Which team has won the most tosses?

matches_df['toss_winner'].value_counts().idxmax()

'Mumbai Indians'

In [ ]:
#6. What does the team decide after winning the toss?

matches_df['toss_decision'].value_counts()

toss_decision
field    496
bat      320
Name: count, dtype: int64

In [ ]:
#7. How does the toss decision vary across seasons?

matches_df.groupby(['season','toss_decision']).size()

season  toss_decision
2008    bat              26
        field            32
2009    bat              35
        field            22
2010    bat              39
        field            21
2011    bat              25
        field            48
2012    bat              37
        field            37
2013    bat              45
        field            31
2014    bat              19
        field            41
2015    bat              25
        field            34
2016    bat              11
        field            49
2017    bat              11
        field            48
2018    bat              10
        field            50
2019    bat              10
        field            50
2020    bat              27
        field            33
dtype: int64

In [ ]:
#8. Does winning the toss imply winning the game?

(matches_df["toss_winner"] == matches_df["winner"]).value_counts()

True     418
False    398
Name: count, dtype: int64

In [ ]:
#9. How many times has the chasing team won the match?

matches_df["chasing_team"] = np.where(
    matches_df["toss_decision"] == "field",
    matches_df["toss_winner"],
    np.where(
        matches_df["team1"] == matches_df["toss_winner"],
        matches_df["team2"],
        matches_df["team1"]
    )
)

len(matches_df[matches_df["chasing_team"] == matches_df["winner"]])

447

In [ ]:
len(matches_df[matches_df["result"] == "wickets"])

435

In [ ]:
#10. Which all teams had won this tournament?

matches_df['winner'].unique()

array(['Kolkata Knight Riders', 'Chennai Super Kings', 'Delhi Daredevils',
       'Royal Challengers Bangalore', 'Rajasthan Royals',
       'Kings XI Punjab', 'Deccan Chargers', 'Mumbai Indians',
       'Pune Warriors', 'Kochi Tuskers Kerala', nan,
       'Sunrisers Hyderabad', 'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals'], dtype=object)

In [ ]:
#11. Which team has played the most number of matches?

pd.concat([matches_df['team1'], matches_df['team2']]).value_counts().idxmax()

'Mumbai Indians'

In [ ]:
#12. Which team has won the most number of times?

matches_df['winner'].value_counts().idxmax()

'Mumbai Indians'

In [ ]:
#13. Which team has the highest winning percentage?



(
    matches_df['winner'].value_counts()
    / pd.concat([matches_df['team1'], matches_df['team2']]).value_counts()
    * 100
).sort_values(ascending=False)

Rising Pune Supergiant         62.500000
Chennai Super Kings            59.550562
Mumbai Indians                 59.113300
Delhi Capitals                 57.575758
Sunrisers Hyderabad            53.225806
Kolkata Knight Riders          51.562500
Rajasthan Royals               50.310559
Royal Challengers Bangalore    46.666667
Kings XI Punjab                46.315789
Gujarat Lions                  43.333333
Kochi Tuskers Kerala           42.857143
Delhi Daredevils               41.614907
Deccan Chargers                38.666667
Rising Pune Supergiants        35.714286
Pune Warriors                  26.086957
Name: count, dtype: float64

In [ ]:
#14. Is there any lucky venue for a particular team?

matches_df.groupby(['venue', 'winner']).size().sort_values(ascending=False)

venue                                      winner
Eden Gardens                               Kolkata Knight Riders      45
Wankhede Stadium                           Mumbai Indians             42
MA Chidambaram Stadium, Chepauk            Chennai Super Kings        40
Sawai Mansingh Stadium                     Rajasthan Royals           32
Rajiv Gandhi International Stadium, Uppal  Sunrisers Hyderabad        30
                                                                      ..
Wankhede Stadium                           Delhi Capitals              1
                                           Pune Warriors               1
                                           Kolkata Knight Riders       1
                                           Rising Pune Supergiants     1
                                           Sunrisers Hyderabad         1
Length: 249, dtype: int64

In [ ]:
#15. Innings wise comparison between teams

balls_df.groupby(['batting_team','inning']).total_runs.sum().unstack()

inning                           1      2
batting_team
Chennai Super Kings          15344  13019
Deccan Chargers               6765   4698
Delhi Capitals                2860   2436
Delhi Daredevils             11247  13038
Gujarat Lions                 2267   2589
Kings XI Punjab              15710  14307
Kochi Tuskers Kerala          1009    892
Kolkata Knight Riders        14842  14541
Mumbai Indians               18338  13948
Pune Warriors                 2973   3385
Rajasthan Royals             11236  13271
Rising Pune Supergiant        1304   1166
Rising Pune Supergiants       1123    940
Royal Challengers Bangalore  15774  14440
Sunrisers Hyderabad          11277   8055

In [ ]:
#16. Which team has scored the most number of 200+ scores?

team_scores=balls_df.groupby(['batting_team','id']).total_runs.sum()
team_scores[team_scores >= 200].groupby('batting_team').count().idxmax()

'Royal Challengers Bangalore'

In [ ]:
#17. Which team has conceded 200+ scores the most?

team_scores = balls_df.groupby(['id', 'batting_team', 'bowling_team'])['total_runs'].sum()
team_scores[team_scores >= 200].groupby('bowling_team').count().idxmax()

'Kings XI Punjab'

In [ ]:
#18. What was the highest run scored by a team in a single match?
balls_df.groupby(['id', 'batting_team'])['total_runs'].sum().idxmax()

(np.int64(598027), 'Royal Challengers Bangalore')

In [ ]:
#19. Which is the biggest win in terms of run margin?

matches_df[matches_df['result'] == 'runs']['result_margin'].max()

146.0

In [ ]:
#20.Which batsmen have played the most number of balls?

balls_df['batsman'].value_counts().idxmax()

'V Kohli'

In [ ]:
#21. Who are the leading run-scorers of all time?

balls_df.groupby('batsman')['batsman_runs'].sum().idxmax()

'V Kohli'

In [ ]:
#22. Who has hit the most number of 4's?

balls_df[
    (balls_df['batsman_runs'] == 4) &
    (balls_df['non_boundary'] == 0)
].groupby('batsman').size().idxmax()

'S Dhawan'

In [ ]:
#23. Who has hit the most number of 6's?

balls_df[
    (balls_df['batsman_runs'] == 6) &
    (balls_df['non_boundary'] == 0)
].groupby('batsman').size().idxmax()

'CH Gayle'

In [ ]:

#24. Who has the highest strike rate?

runs = balls_df.groupby('batsman')['batsman_runs'].sum()

balls_faced = balls_df[balls_df['extras_type'] != 'wides'].groupby('batsman').size()

strike_rate = (runs / balls_faced) * 100
strike_rate.idxmax()

'B Stanlake'

In [ ]:
#25. Who is the leading wicket-taker?

balls_df[balls_df['is_wicket']==1].groupby('bowler').size().idxmax()

'SL Malinga'

In [ ]:
#26. Which stadium has hosted the most number of matches?

matches_df['venue'].value_counts().idxmax()

'Eden Gardens'

In [ ]:
#27. Who has won the most MOM awards?

matches_df['player_of_match'].value_counts().idxmax()

'AB de Villiers'

In [ ]:
#28. What is the count of fours hit in each season?

merged_df[
    (merged_df['batsman_runs'] == 4) &
    (merged_df['non_boundary'] == 0)
].groupby('season').size()

season
2008    1703
2009    1316
2010    1708
2011    1913
2012    1911
2013    2051
2014    1562
2015    1607
2016    1632
2017    1609
2018    1651
2019    1653
2020    1582
dtype: int64

In [ ]:
#29. What is the count of sixes hit in each season?

merged_df[
    (merged_df['batsman_runs'] == 6) &
    (merged_df['non_boundary'] == 0)
].groupby('season').size()

season
2008    622
2009    506
2010    585
2011    639
2012    731
2013    674
2014    714
2015    692
2016    638
2017    705
2018    872
2019    784
2020    734
dtype: int64

In [ ]:
#30. What is the count of runs scored from boundaries in each season?


merged_df[
    (merged_df['batsman_runs'].isin([4, 6])) &
    (merged_df['non_boundary'] == 0)
].groupby('season')['batsman_runs'].sum()

season
2008    10544
2009     8300
2010    10342
2011    11486
2012    12030
2013    12248
2014    10532
2015    10580
2016    10356
2017    10666
2018    11836
2019    11316
2020    10732
Name: batsman_runs, dtype: int64

In [ ]:
#31. What is the run contribution from boundaries in each season?


boundary_runs = merged_df[
    (merged_df['batsman_runs'].isin([4, 6])) &
    (merged_df['non_boundary'] == 0)
].groupby('season')['batsman_runs'].sum()

total_runs = merged_df.groupby('season')['total_runs'].sum()

run_contribution = (boundary_runs / total_runs) * 100

run_contribution.round(2)

season
2008    58.78
2009    50.86
2010    54.82
2011    54.30
2012    53.58
2013    54.34
2014    55.70
2015    57.71
2016    54.90
2017    56.83
2018    59.47
2019    58.33
2020    55.46
dtype: float64

In [ ]:
#32. Which team has scored the most runs in the first 6 overs?


first_6_overs = balls_df[balls_df['over'] < 6]

first_6_overs.groupby('batting_team')['total_runs'].sum().sort_values(ascending=False)

batting_team
Mumbai Indians                 9204
Kings XI Punjab                8907
Kolkata Knight Riders          8871
Royal Challengers Bangalore    8699
Chennai Super Kings            8048
Delhi Daredevils               7349
Rajasthan Royals               7151
Sunrisers Hyderabad            5917
Deccan Chargers                3417
Pune Warriors                  1895
Delhi Capitals                 1560
Gujarat Lions                  1553
Rising Pune Supergiant          785
Kochi Tuskers Kerala            680
Rising Pune Supergiants         638
Name: total_runs, dtype: int64

In [ ]:
#33. Which team has scored the most runs in the last 4 overs?

last_4_overs = balls_df[balls_df['over'] >= 16]

last_4_overs.groupby('batting_team')['total_runs'].sum().sort_values(ascending=False)

batting_team
Mumbai Indians                 7538
Royal Challengers Bangalore    6787
Chennai Super Kings            6655
Kings XI Punjab                6227
Kolkata Knight Riders          6224
Rajasthan Royals               5043
Delhi Daredevils               5043
Sunrisers Hyderabad            4155
Deccan Chargers                2539
Pune Warriors                  1360
Delhi Capitals                 1160
Gujarat Lions                   921
Rising Pune Supergiant          555
Rising Pune Supergiants         443
Kochi Tuskers Kerala            337
Name: total_runs, dtype: int64

In [ ]:
#34. Which team has the best scoring run-rate in the first 6 overs?

first_6_overs = balls_df[balls_df['over'] < 6]

run_rate = (
    first_6_overs.groupby('batting_team')['total_runs'].sum() / 6
).idxmax()

run_rate

'Mumbai Indians'

In [ ]:
#35. Which team has the best scoring run-rate in the last 4 overs?
last_4_overs = balls_df[balls_df['over'] >= 16]

run_rate = (
    last_4_overs.groupby('batting_team')['total_runs'].sum() / 4
).sort_values(ascending=False)

run_rate

batting_team
Mumbai Indians                 1884.50
Royal Challengers Bangalore    1696.75
Chennai Super Kings            1663.75
Kings XI Punjab                1556.75
Kolkata Knight Riders          1556.00
Rajasthan Royals               1260.75
Delhi Daredevils               1260.75
Sunrisers Hyderabad            1038.75
Deccan Chargers                 634.75
Pune Warriors                   340.00
Delhi Capitals                  290.00
Gujarat Lions                   230.25
Rising Pune Supergiant          138.75
Rising Pune Supergiants         110.75
Kochi Tuskers Kerala             84.25
Name: total_runs, dtype: float64